# -*- coding: utf-8 -*-
"""Web scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CJRLLmT5ICg4Id2riYR6tbG67591qgRj

# **Web scraping

With help of BeautifulSoup I collect the data from the webpage. Once the data is collected and made a table, I have saved it into a local .csv file. after that I analysis the data.

1.   List item
2.   List item



The websitelink is : https://www.airlinequality.com/airline-reviews/british-airways
"""

!pip install requests
!pip install html5lib
!pip install bs4

import requests
from bs4 import BeautifulSoup
import pandas as pd

"""Create URL to collect links"""

url = 'https://www.airlinequality.com/airline-reviews/british-airways'

"""Collect HTML data from this page"""

r = requests.get(url)
htmlcontent = r.content

soup = BeautifulSoup(htmlcontent, 'html.parser')    ##cheacking
soup

"""Parse *content* and build the dataframe

"""

ase_url = "https://www.airlinequality.com/airline-reviews/british-airways"
pages = 10 #10
page_size = 100 #100

reviews = []
aircraft = []
seat_type = []
route = []
recommended = []
df = pd.DataFrame()

# for i in range(1, pages + 1):
for i in range(1, pages + 1):

    rating = []
    category = []

    print(f"Scraping page {i}")

    # Collect HTML data from this page
    response = requests.get(url)

    # Parse content
    content = response.content
    soup = BeautifulSoup(content, 'html.parser')
    for para in soup.find_all("div", {"class": "text_content"}):
        reviews.append(para.get_text())

    for para2 in soup.find_all("div", {"class" : "review-stats"}):
        for para3 in para2.find_all('td',{'class' : 'review-value'}):
            rating.append(para3.get_text())
        recomend = rating[-1]
        rating = rating[:-1]

        for para4 in para2.find_all('td',{'class' : 'review-rating-stars stars'}):
            para5 = len(para4.find_all('span', {'class' : 'star fill'}))
            rating.append(para5)
        rating.append(recomend)


        for para6 in para2.find_all('td',{'class' : 'review-rating-header'}):
            category.append(para6.get_text())


        # Build the dataframe from the dictionary.
        data_dict = pd.DataFrame([rating], columns=category)
        df = df.append(data_dict, ignore_index=True).reset_index(drop=True)

        rating = []
        category = []

    print(f"   ---> {len(reviews)} total reviews")

df["reviews"] = reviews

df.head()



"""Saving the data"""

df.to_csv("BA_reviews.csv", index=False)

df= pd.read_csv("/content/BA_reviews.csv")

df.shape

"""clean this data to remove any unnecessary text from each of the rows. like "✅ Trip Verified" can be removed from each row (if it exists)"""

remove_text = ['✅ Trip Verified', 'Not Verified |']

for i in range(len(df['reviews'])):
    for j in remove_text:
        if j in df['reviews'][i]:
            df['reviews'] = df['reviews'].str.replace(j,'')

df.head()

"""# **Analysis Data**"""

!pip install WordCloud

from wordcloud import WordCloud
wordcloud = WordCloud(width = 1000, height = 450, background_color = 'white').generate(unique_string)
plt.figure(figsize=(12,8))

# Display the generated image:
plt.imshow(wordcloud)
plt.axis("off")
plt.show()

"""From the wordcloud above, It seems that the key of topics in customer review are flight, seat , service and time. showing that people are actively talking about their experience on the plane and the staff."""